### ISSUE TITLE
Final Group Capstone Project 

### ISSUE THREAD

**Issue by elarhadu** [asharanjith/stay-a-while-front-end#14]
# Hello Code Reviewer 👋 👋 
![image](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWRiNjU1OWY5NjZmYzZjNGU1OGFlODgyYmE2YzI2NTU0MzBiYjA3YSZjdD1n/SbKNFpFZEumGTkgPgA/giphy.gif)

## For this capstone project, we are made up of a  group of 4 team members. We are;
- [Asha](@asharanjith)
- [Elarh](@elarhadu)
- [Samuel](@admirerbrown)
- [Rohit](@rbhatt1999)

## This is a [link](https://github.com/users/asharanjith/projects/5/views/1?layout=board) to our Kanban Board and a screenshot has been attached to this issue

![image](https://user-images.githubusercontent.com/105938633/235927703-87bd44cf-f336-449b-a0bc-043b499c970d.png)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- Met all requirements 👍 
- Like that you separated the back and frontend task
## Optional suggestions
- Consider using labels to help further identify and filter tasks by type

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
